from enum import Enum as PyEnum

class AccountStatusEnum(PyEnum):
    RECENTLY_INGESTED = "RECENTLY_INGESTED"
    GOOD_STANDING = "GOOD_STANDING"
    LOCKED = "LOCKED"
    TERMINATED = "TERMINATED"
    CAPTCHA = "CAPTCHA"
    COMPROMISED_LOCKED = "COMPROMISED_LOCKED"
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
    OBFUSCATED_PHONE = 'OBFUSCATED_PHONE'
    CHATBOT_LOCKED = "CHATBOT_LOCKED"
    TEMPORARY_LOCKED = "TEMPORARY_LOCKED"
