from enum import Enum as PyEnum

class ExecutionTypeEnum(PyEnum):
    QUICK_ADDS = "QUICK_ADDS"
    SEND_TO_USER = "SEND_TO_USER"
    CHECK_FRIENDS = "CHECK_FRIENDS"
    REMOVE_FRIENDS = "REMOVE_FRIENDS"
    CHECK_CONVERSATIONS = "CHECK_CONVERSATIONS"
    STATUS_CHECK = "STATUS_CHECK"
    COMPUTE_STATISTICS = "COMPUTE_STATISTICS"
    GENERATE_LEADS = "GENERATE_LEADS"
    CONSUME_LEADS = "CONSUME_LEADS"
    QUICK_ADDS_TOP_ACCOUNTS = "QUICK_ADDS_TOP_ACCOUNTS"
    SET_BITMOJI = "SET_BITMOJI"
    CHANGE_BITMOJI = 'CHANGE_BITMOJI'