from enum import Enum as PyEnum

class StatusEnum(PyEnum):
    STARTED = "STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    FAILURE = "FAILURE"
    SNAPKAT_API_RATE_LIMIT_EXCEEDED = "SNAPKAT_API_RATE_LIMIT_EXCEEDED"
    EXECUTION_ALREADY_IN_PROGRESS = "EXECUTION_ALREADY_IN_PROGRESS"
    PLATFORM_RATE_LIMIT_EXCEEDED = "PLATFORM_RATE_LIMIT_EXCEEDED"