# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argos.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'argos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rgos.proto\x12\rsnap.security\"G\n\x1aTokenWithSecurityClearance\x12\r\n\x05token\x18\x01 \x01(\x0c\x12\x1a\n\x12security_clearance\x18\x02 \x01(\x07\"o\n\nArgosToken\x12>\n\x0b\x61rgos_token\x18\x01 \x01(\x0b\x32).snap.security.TokenWithSecurityClearance\x12\x11\n\tvalid_for\x18\x02 \x01(\x05\x12\x0e\n\x06method\x18\x04 \x01(\x05\"2\n\x15\x41rgosGetTokensRequest\x12\x19\n\x11\x61ttestation_token\x18\x01 \x01(\x0c\"e\n\rArgosResponse\x12)\n\x06token1\x18\x01 \x01(\x0b\x32\x19.snap.security.ArgosToken\x12)\n\x06token2\x18\x02 \x01(\x0b\x32\x19.snap.security.ArgosToken\"X\n\x16\x41rgosGetTokensResponse\x12\x0e\n\x06random\x18\x01 \x01(\x05\x12.\n\x08response\x18\x02 \x01(\x0b\x32\x1c.snap.security.ArgosResponseB\x1cH\x02\xaa\x02\x17SnapProto.Snap.Securityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002\252\002\027SnapProto.Snap.Security'
  _globals['_TOKENWITHSECURITYCLEARANCE']._serialized_start=30
  _globals['_TOKENWITHSECURITYCLEARANCE']._serialized_end=101
  _globals['_ARGOSTOKEN']._serialized_start=103
  _globals['_ARGOSTOKEN']._serialized_end=214
  _globals['_ARGOSGETTOKENSREQUEST']._serialized_start=216
  _globals['_ARGOSGETTOKENSREQUEST']._serialized_end=266
  _globals['_ARGOSRESPONSE']._serialized_start=268
  _globals['_ARGOSRESPONSE']._serialized_end=369
  _globals['_ARGOSGETTOKENSRESPONSE']._serialized_start=371
  _globals['_ARGOSGETTOKENSRESPONSE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
