# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCAtlasEmojiInfo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'SCAtlasEmojiInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SCAtlasEmojiInfo.proto\x12\x18\x63om.snapchat.atlas.proto\"\x97\x03\n\x10SCAtlasEmojiInfo\x12I\n\x04type\x18\x01 \x01(\x0e\x32;.com.snapchat.atlas.proto.SCAtlasEmojiInfo.SCAtlasEmojiType\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x18\n\x10\x65mojiDescription\x18\x04 \x01(\t\x12\x1e\n\x16\x65mojiPickerDescription\x18\x05 \x01(\t\x12P\n\x0b\x64\x65\x66\x61ultType\x18\x06 \x01(\x0e\x32;.com.snapchat.atlas.proto.SCAtlasEmojiInfo.SCAtlasEmojiType\x12\x14\n\x0c\x64\x65\x66\x61ultValue\x18\x07 \x01(\t\x12\x17\n\x0f\x65mojiLegendRank\x18\x08 \x01(\x05\"^\n\x10SCAtlasEmojiType\x12#\n\x1fSCAtlasEmojiType_EmojiTypeUnset\x10\x00\x12%\n!SCAtlasEmojiType_EmojiTypeUnicode\x10\x01\x42\x31H\x02\xa2\x02\x07SCAtlas\xaa\x02\"SnapProto.Com.Snapchat.Atlas.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCAtlasEmojiInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002\242\002\007SCAtlas\252\002\"SnapProto.Com.Snapchat.Atlas.Proto'
  _globals['_SCATLASEMOJIINFO']._serialized_start=53
  _globals['_SCATLASEMOJIINFO']._serialized_end=460
  _globals['_SCATLASEMOJIINFO_SCATLASEMOJITYPE']._serialized_start=366
  _globals['_SCATLASEMOJIINFO_SCATLASEMOJITYPE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
