# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCAtlasFriendmoji.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'SCAtlasFriendmoji.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SCAtlasEmojiInfo_pb2 as SCAtlasEmojiInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17SCAtlasFriendmoji.proto\x12\x18\x63om.snapchat.atlas.proto\x1a\x16SCAtlasEmojiInfo.proto\"m\n\x16SCAtlasExtraFriendmoji\x12\x14\n\x0c\x63\x61tegoryName\x18\x01 \x01(\t\x12=\n\temojiInfo\x18\x02 \x01(\x0b\x32*.com.snapchat.atlas.proto.SCAtlasEmojiInfo\"A\n\x11SCAtlasFriendmoji\x12\x14\n\x0c\x63\x61tegoryName\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationTime\x18\x02 \x01(\x03\x42\x31H\x02\xa2\x02\x07SCAtlas\xaa\x02\"SnapProto.Com.Snapchat.Atlas.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCAtlasFriendmoji_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002\242\002\007SCAtlas\252\002\"SnapProto.Com.Snapchat.Atlas.Proto'
  _globals['_SCATLASEXTRAFRIENDMOJI']._serialized_start=77
  _globals['_SCATLASEXTRAFRIENDMOJI']._serialized_end=186
  _globals['_SCATLASFRIENDMOJI']._serialized_start=188
  _globals['_SCATLASFRIENDMOJI']._serialized_end=253
# @@protoc_insertion_point(module_scope)
