# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SCBitmojiBackgroundURL.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'SCBitmojiBackgroundURL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSCBitmojiBackgroundURL.proto\x12\x1bsnapchat.bitmoji.profile.v1\"\x8c\x02\n\x1dSCBitmojiBitmojiBackgroundURL\x12u\n\x04type\x18\x01 \x01(\x0e\x32g.snapchat.bitmoji.profile.v1.SCBitmojiBitmojiBackgroundURL.SCBitmojiBitmojiBackgroundURL_BackgroundType\x12\x15\n\rbackgroundURL\x18\x02 \x01(\t\"]\n,SCBitmojiBitmojiBackgroundURL_BackgroundType\x12\x1d\n\x19\x42\x41\x43KGROUND_URL_TYPE_UNSET\x10\x00\x12\x0e\n\nGENERATIVE\x10\x01\x42\x36H\x02\xa2\x02\tSCBitmoji\xaa\x02%SnapProto.Snapchat.Bitmoji.Profile.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SCBitmojiBackgroundURL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002\242\002\tSCBitmoji\252\002%SnapProto.Snapchat.Bitmoji.Profile.V1'
  _globals['_SCBITMOJIBITMOJIBACKGROUNDURL']._serialized_start=62
  _globals['_SCBITMOJIBITMOJIBACKGROUNDURL']._serialized_end=330
  _globals['_SCBITMOJIBITMOJIBACKGROUNDURL_SCBITMOJIBITMOJIBACKGROUNDURL_BACKGROUNDTYPE']._serialized_start=237
  _globals['_SCBITMOJIBITMOJIBACKGROUNDURL_SCBITMOJIBITMOJIBACKGROUNDURL_BACKGROUNDTYPE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
